### ISSUE TITLE
There is no place to put a token.

### ISSUE THREAD

**Issue by nanospearing** [DavidQF555/MusicBot#1]
I have no idea where to put my token, or any configs at all. May i please have some help?

**Comment by DavidQF555** [comment]
There is a place, but it's just not very obvious because I haven't created a read me yet. Create a file named .env within the most outer folder and write TOKEN="whatever". There are also 2 other variables required here for the bot, which are CLIENT_ID and YT_DATA_KEY. The client ID is just the client ID of the bot and the YT data key is a key given when creating credentials for YouTube Data API. Just write those 2 on separate lines after the token. Make sure that the values are surrounded by quotes and there are no spaces.

**Comment by nanospearing** [comment]
Ok, thank you for this info!
